const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const doc = new PDFDocument({
  margin: 40,
  size: 'A4'
});

const outputPath = path.join(__dirname, '..', 'Agentify_Product_Showcase.pdf');
doc.pipe(fs.createWriteStream(outputPath));

// Primary Colors
const primaryColor = '#4f46e5';
const secondaryColor = '#06b6d4';
const darkTextColor = '#1e293b';
const lightMutedColor = '#64748b';
const cardBg = '#f8fafc';

// Header
doc
  .fillColor(primaryColor)
  .fontSize(24)
  .font('Helvetica-Bold')
  .text('Agentify AI™', { align: 'center' });

doc
  .fillColor(secondaryColor)
  .fontSize(12)
  .font('Helvetica-Bold')
  .text('AUTONOMOUS AI SALES, SUPPORT & ORDER JOURNEY SUITE', { align: 'center' });

doc.moveDown(0.5);

doc
  .fillColor(lightMutedColor)
  .fontSize(10)
  .font('Helvetica')
  .text('Official Feature & Capabilities Marketing Showcase', { align: 'center' });

doc.moveDown(1);
doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(40, doc.y).lineTo(555, doc.y).stroke();
doc.moveDown(1);

// Features definition list
const features = [
  {
    icon: '🧠',
    title: 'Agentify OmniMind™ (Multi-Agent AI Engine)',
    tagline: 'Autonomous conversational intelligence & RAG knowledge base',
    details: [
      'ConverseIQ™: Intelligent Receptionist AI for product advice & store inquiries.',
      'LeadCapture Pro™: Autonomous lead detection & qualification engine (Name, Email, Phone).',
      'PersonaFlex™: Instant switching between Warm & Conversational or Corporate Professional tones.',
      'RAG Vector Vault™: 768-dim pgvector embeddings built from web crawling & PDF parsing.'
    ]
  },
  {
    icon: '🛍️',
    title: 'Shopify Pulse™ (Seamless E-Commerce Integration)',
    tagline: 'Real-time order tracking & automated catalog management',
    details: [
      'OrderJourney 360™: Live order lookup using Order # + Email/Phone verification.',
      'CatalogSync Engine™: Real-time inventory sync via Shopify Admin GraphQL API.',
      'Storefront App Block: One-click Shopify Theme Extension integration (chatbot.liquid).'
    ]
  },
  {
    icon: '🎯',
    title: 'LeadFlow 360™ (Prospect Conversion Pipeline)',
    tagline: 'Instant merchant alerts & customer follow-up email engine',
    details: [
      'Real-Time Merchant Alerts: Instant Nodemailer email notifications on lead capture.',
      'Automated Customer Confirmation: Branded follow-up emails sent directly to prospects.',
      'Lead Command Center: Dedicated admin dashboard (/admin/shopify/leads) to track prospects.'
    ]
  },
  {
    icon: '📊',
    title: 'Agentify Insights™ (Performance Analytics)',
    tagline: 'Data visualization and ROI metrics for store owners',
    details: [
      'Executive KPI Dashboard: Live tracking of chat volumes, lead conversions, and sync status.',
      'Visual Growth Analytics: Recharts-powered interactive monthly trend analytics.'
    ]
  },
  {
    icon: '🎨',
    title: 'Widget Studio Pro™ (Custom Storefront Widget)',
    tagline: 'Shadow DOM isolated widget for zero style conflicts',
    details: [
      'Shadow DOM Isolation: Guaranteed zero CSS leakage into website themes.',
      'Custom Brand Theme Engine: Primary color picker, logo upload, and custom welcome prompts.',
      'Universal Script Embed: Drop-in JavaScript widget (public/widget.js) for any website.'
    ]
  },
  {
    icon: '🤝',
    title: 'Human-in-the-Loop Handoff™ (Hybrid Support)',
    tagline: 'Seamless takeover from AI to live human support staff',
    details: [
      'One-Touch Mode Switch: Seamless transition from AI automation to live human agent support.',
      'Preserved Context: Full chat conversation history preserved for human support team.'
    ]
  }
];

features.forEach((feat) => {
  // Feature box
  doc
    .fillColor(primaryColor)
    .fontSize(14)
    .font('Helvetica-Bold')
    .text(`${feat.title}`);

  doc
    .fillColor(secondaryColor)
    .fontSize(9)
    .font('Helvetica-Oblique')
    .text(feat.tagline);

  doc.moveDown(0.3);

  feat.details.forEach((item) => {
    doc
      .fillColor(darkTextColor)
      .fontSize(9.5)
      .font('Helvetica')
      .text(`  •  ${item}`, { indent: 10 });
  });

  doc.moveDown(0.8);
});

// Footer
doc
  .fontSize(8)
  .fillColor(lightMutedColor)
  .text('Generated by Kriotek Agentify AI — Confidential & Proprietary Product Showcase', 40, 780, {
    align: 'center',
    width: 515
  });

doc.end();
console.log('High-quality PDF generated successfully at:', outputPath);
